# Default values for cnj-hello-backend-jakartaee.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ${docker.image.name}
  tag: ${project.version}
  pullPolicy: IfNotPresent
#  pullSecret: fwp-pull-secret

probes:
  readiness:
    path: /api/v1/probes/readiness
  liveness:
    path: /api/v1/probes/liveness

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
    traefik.http.middlewares.example.stripprefix.prefixes: /${k8s.ingress.path}
  rules:
    - host: "${k8s.ingress.host}"
      paths: ["${k8s.ingress.path}"]
  tls: []

resources:
  limits:
    #   cpu: 100m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 756Mi

nodeSelector: {}

tolerations: []

affinity: {}
