---
kind: pipeline
type: kubernetes
name: docker-build

steps:
  - name: test-commit-stage
    image: docker.at41tools.k8s.aws.msgoat.eu/cloudtrain/cnj-drone-build-mvn
    commands:
      - pwd
      - ls -al .
      - whoami
      - mvn clean deploy -f cnj-hello-backend-test/pom.xml --batch-mode --fail-fast --debug --errors -V -U -Dsurefire.useFile=false --activate-profiles commit-stage
  - name: javaee-commit-stage
    image: docker.at41tools.k8s.aws.msgoat.eu/cloudtrain/cnj-drone-build-mvn
    commands:
      - mvn clean deploy -f cnj-hello-backend-javaee/pom.xml --batch-mode --fail-fast --errors -V -U -Dsurefire.useFile=false --activate-profiles commit-stage -Dtest.target.route=http://10.118.17.191:38080
  - name: javaee-integration-test-stage
    image: docker.at41tools.k8s.aws.msgoat.eu/cloudtrain/cnj-drone-build-mvn
    commands:
      - mvn clean verify -f cnj-hello-backend-javaee/pom.xml --batch-mode --fail-fast --errors -V -U -Dsurefire.useFile=false --activate-profiles integration-test-stage
  - name: micro-commit-stage
    image: docker.at41tools.k8s.aws.msgoat.eu/cloudtrain/cnj-drone-build-mvn
    commands:
      - mvn clean deploy -f cnj-hello-backend-micro/pom.xml --batch-mode --fail-fast --errors -V -U -Dsurefire.useFile=false --activate-profiles commit-stage -Dtest.target.route=http://10.118.17.191:38080
  - name: micro-integration-test-stage
    image: docker.at41tools.k8s.aws.msgoat.eu/cloudtrain/cnj-drone-build-mvn
    commands:
      - mvn clean verify -f cnj-hello-backend-micro/pom.xml --batch-mode --fail-fast --errors -V -U -Dsurefire.useFile=false --activate-profiles integration-test-stage
  - name: spring-commit-stage
    image: docker.at41tools.k8s.aws.msgoat.eu/cloudtrain/cnj-drone-build-mvn
    commands:
      - mvn clean deploy -f cnj-hello-backend-spring/pom.xml --batch-mode --fail-fast --errors -V -U -Dsurefire.useFile=false --activate-profiles commit-stage -Dtest.target.route=http://10.118.17.191:38080
  - name: spring-integration-test-stage
    image: docker.at41tools.k8s.aws.msgoat.eu/cloudtrain/cnj-drone-build-mvn
    commands:
      - mvn clean verify -f cnj-hello-backend-spring/pom.xml --batch-mode --fail-fast --errors -V -U -Dsurefire.useFile=false --activate-profiles integration-test-stage
